#!/usr/bin/env bash

local_dir=`dirname "$0"`
tests=$local_dir/tests
unit=0
while [ "$1" != "" ]; do
    case $1 in
        -u | --unit )           unit=1
                                tests=$local_dir/tests/unit
                                ;;
    esac
    shift
done


if [ $unit != 1 ]; then
  echo "Setting up Redis"
  docker-compose -f $local_dir/tests/docker-compose.yml up &
  sleep 2
fi

echo "Running tests"
PYTHONPATH=$local_dir/src pytest \
  --cov-report html:$local_dir/test_output \
  --cov=$local_dir/src \
  -o cache_dir=$local_dir/.my_cache_dir \
  $tests

if [ $unit != 1 ]; then
  echo "Taking down Redis"
  docker-compose -f $local_dir/tests/docker-compose.yml down
fi
